project:
  type: website
  output-dir: _site


website:
  title: "Portefølje | Lars Martin Tingelstad" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/project_3_strava/
        text: Strava
      - href: projects/project_phd_paper3/
        text: PhD
      - href: projects/project_2_Bike_Store/
        text: Bike Store
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

