project:
  type: website
  output-dir: _site


website:
  title: "Lars Martin Tingelstad, PhD" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/project_3_strava/
        text: Strava
      - href: projects/project_2_Bike_Store/
        text: Bike Store
      - href: projects/project_1_salg_lønnsomhetsanalyse/
        text: Lønnsomhetsanalyse


format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

